# 발표 소단원 리스트

(2, 17)
(3, 1)
(3, 5)
(3, 9)
(3, 13)
(4, 1)
(4, 5)
(4, 9)

# 전체 요약자료

- 2.17 : HTML, XML을 생성할 때 특수 문자를 이스케이핑(escaping)하는 과정 = html.escape() / 반대로 디코딩 : html.unescape()
- 3.1 : 반올림 round(value, ndigits) 함수
- 3.5 : 바이트 문자열 <-> 정수값 변환 : int.to_bytes() / int.from_bytes()
- 3.9 : 빠르고 효율적인 수학 계산을 위해 NumPy 모듈 사용
- 3.13 : 날짜 계산 -> datetime 모듈
- 4.1 : for문 대신 수동으로 이터레이터 소비 = next() 함수
- 4.5 : 역방향 순환 = reversed() / __reversed__() 메소드 구현
- 4.9 : 순열, 조합 = itertools 모듈 (combinations, permutations)


In [46]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### 2.17 HTML과 xml 엔티티 처리
- <, >, & 과 같은 특정 문자를 피하고 싶을 때
- HTML, XML 엔티티를 이에 일치파는 문자로 치환하고 싶을 때

ex) http://a.com?name=egoing&job=programmer 에서
&job=programmer 중 '&'는 하나의 파라미터가 끝나고 다음 파라미터가 온다는 의미이다.
그런데 다음과 같이 job의 값에 &가 포함된다면 시스템은 job의 값을 제대로 인식할수 없게 된다.
http://a.com?name=egoing&job=programmer&blogger
이런 문제를 회피하기 위해서 다음과 같이 치환해준다.
http://a.com?name=egoing&job=programmer%26blogger
그럼 시스템에서는 %26을 &로 해석하고 의도대로 해석할 수 있게 된다.
이러한 처리를 이스케이핑(escaping)라고 부른다.

- escape(string) : URI로 데이터를 전달하기 위해서 문자열을 인코딩 -> return string(인코딩된 문자열을 반환)

In [9]:
import html
s = 'Elements are written as "<tag>text</tag>".'
print(html.escape(s))

Elements are written as &quot;&lt;tag&gt;text&lt;/tag&gt;&quot;.


위와 같이 html escape 문자들을 unescape 해서 스트링으로 변환
HTML, XML을 처리하려면 올바른 HTML, XML 파서를 사용해야 함
- html.parser
- xml.entree.ElementTree

와 같은 파싱 모듈로 HTML, XML을 처리하면 기본적인 내용을 알아서 다 처리해줌

- unescape(encodedURI) -> return string(디코딩된 문자열)

In [18]:
from html.parser import HTMLParser #HTMLParser.unescape() 함수는 삭제될 예정이라고 함
s = 'Spicy &quot;Jalape&#241;o&quot.'
html.unescape(s)

from xml.sax.saxutils import unescape
t = 'The prompt is &gt;&gt;&gt;'
unescape(t)

'Spicy "Jalapeño".'

'The prompt is >>>'

### 3.1 반올림
- round(value, ndigits) 함수

In [19]:
round(1.243424, 4)

#값이 두 선택지의 가운데 있으면 더 가까운 짝수가 됨
round(2.5)

# ndigits 자리에 음수 가능 -> 10의 자리, 100의 자리로 생각하면 됨
round(30243, -1)

1.2434

2

반올림과 서식화는 다름
-> 특정 자릿수까지 숫자를 표현하고 싶으면 서식화 사용

In [14]:
x = 1.23456
format(x, '0.3f')

'1.235'

### 3.5 바이트에서 큰 숫자를 패킹/언패킹
- 바이트 문자열을 언패킹해서 정수 값으로 만들 때 : int.from_bytes(bytes, byteorder)
- 매우 큰 정수 값을 바이트 문자열로 변환할 때 : int.to_bytes(byte length, byteorder)

 ex) 보통 네트워크나 암호화가 필요할 때 : IPv6 네트워크 주소는 128형 정수형으로 표시

In [20]:
#  byteorder = "big" : 최상위 바이트는 바이트 배열의 처음에 있습니다. 
# byteorder = "little" :  최상위 바이트는 바이트 배열의 끝
data = b'\x00]x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
int.from_bytes(data, 'little')
int.from_bytes(data, 'big')

1159650660216490670940610118899223377206598912

8142341868532351008491168493266913819033652

In [21]:
# int.to_bytes( byte length, byteorder)
x = 939240400248248493490034888191
x.to_bytes(16, 'big')
x.to_bytes(16, 'little')

b'\x00\x00\x00\x0b\xda\xd9s\x19\xc3\xe9\xd4\xe7%f\xcd\xff'

b'\xff\xcdf%\xe7\xd4\xe9\xc3\x19s\xd9\xda\x0b\x00\x00\x00'

### 3.9 큰 배열 계산
- 배열이나 그리드와 같이 커다란 숫자 데이터세트에 계산
- import Numpy

 Numpy 라이브러리는 표준 파이썬 리스트보다 수학 계산에 훨씬 효율적.

In [47]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x * 2
x + y
x + 10

[1, 2, 3, 4, 1, 2, 3, 4]

[1, 2, 3, 4, 5, 6, 7, 8]

TypeError: can only concatenate list (not "int") to list

In [24]:
# 스칼라 연산 기반
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2
ax + ay
ax + 10

array([2, 4, 6, 8])

array([ 6,  8, 10, 12])

array([11, 12, 13, 14])

In [26]:
#수학 연산이 모든 요소에 동시 적용
def f(x) :
    return 3*x**2 - 2*x + 3

f(ax)

array([ 4, 11, 24, 43])

In [27]:
#math 모듈같이 일반 함수 제공
np.sqrt(ax)
np.cos(ax)
# math 모듈 함수로 계산하는 것보다 수백 배 빠름!!!!!

array([1.        , 1.41421356, 1.73205081, 2.        ])

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

- NumPy 배열은 동일한 데이터 타입을 메모리에 연속으로 나열

-> 파이썬 리스트보다 훨씬 더 큰 배열을 만들 수 있음

In [29]:
grid = np.zeros(shape=(10000, 10000), dtype = float)
grid
grid += 10
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

- 다차원 배열의 인덱싱 기능을 확장하고 있음

In [32]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a
a[1] #첫번째 row
a[:,1] #첫번째 column
a[1:3, 1:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([5, 6, 7, 8])

array([ 2,  6, 10])

array([[ 6,  7],
       [10, 11]])

In [34]:
a[1:3, 1:3] += 10
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [35]:
np.where(a<10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

### 3.13 마지막 금요일 날짜 구하기

In [37]:
from datetime import datetime, timedelta
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
           'Friday', 'Saturday', 'Sunday']

def get_previous_byday(dayname, start_date = None):
    if start_date is None :
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) & 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days = days_ago)
    return target_date

datetime.today()
get_previous_byday('Monday')

datetime.datetime(2019, 3, 20, 23, 45, 59, 1231)

datetime.datetime(2019, 3, 19, 23, 45, 59, 3775)

In [ ]:
날짜 계산을 많이 수행한다면 python-dateutil 패키지 설치 추천 

In [48]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.rrule import *
d = datetime.now()
print(d)

#다음 금요일
print(d + relativedelta(weekday=FR))

#마지막 금요일
print(d + relativedelta(weekday=FR(-1)))

2019-03-23 00:37:26.565323
2019-03-29 00:37:26.565323
2019-03-22 00:37:26.565323


### 4.1 수동으로 이터레이터 소비
- for 문을 사용하지 않고 순환 가능한 아이템에 접근하기 = next() 함수

StopIteration : 순환의 끝을 알리는 데 사용

In [6]:
#파일에서 줄을 읽는 코드
ex = iter(['a','b','c'])
try:
    while True:
        line = next(ex)
        print(line, end=' ')
except StopIteration :
    pass

a b c 

- next(iterable, default) : 반복자를 입력받아 다음 출력값을 반환하는 함수

iterable : 필수(iterable object), default : optional(An default value to return if the iterable has reached to its end)

next()를 수동으로 사용 -> None과 같은 종료 값을 반환

In [11]:
ex2 = iter([1,2,3,4])
while True:
    line = next(ex2, None)
    if line is None:
        break
    print(line, end='')

1234

### 4.5 역방향 순환
- 시퀀스 아이템을 역방향으로 순환 : 내장함수 reversed()

역방향 순환은 객체가 __reversed__() 특별 메소드를 구현하고 있거나 크기를 알 수 있는 경우에만 가능

둘 다 아니면 객체를 먼저 리스트로 변환해야 함. (메모리 소모 큼)

In [49]:
a = [1,2,3,4]
for x in reversed(a):
    print(x)

4
3
2
1


__reversed__() 메소드를 구현하면 사용자 정의 클래스에서 역방향 순환이 가능함

-> 효율적 + 데이터를 리스트로 변환하고 순환하는 수고를 덜어줌

In [38]:
class countdown :
    def __init__(self, start):
        self.start = start
    
    #순방향 순환
    def __iter__(self):
        n = self.start
        while n > 0:
            yield n
            n-=1
            
    #역방향 순환
    def __reversed__(self):
        n = 1
        while n <= self.start:
            yield n
            n += 1

ex = countdown(5)

print('Countdown :')
for i in iter(ex):
    print(i, end=' ')

print('\nCountup :')
for i in reversed(ex):
    print(i, end=' ')


Countdown :
5 4 3 2 1 
Countup :
1 2 3 4 5 

### 4.9 가능한 모둔 순열과 조합 순환
- itertools.permutations() : 모든 순열 생성
- itertools.combinations() : 모든 조합 생성
- itertools.combinations_with_replacement : 중복 조합

In [43]:
items = ['a', 'b', 'c']
from itertools import permutations
for p in permutations(items):
    print(p)
    
#더 짧은 길이의 순열을 원할 때 :
print('\n길이가 2인 순열 :')
for p in permutations(items, 2):
    print(p)

('a', 'b', 'c')
('a', 'c', 'b')
('b', 'a', 'c')
('b', 'c', 'a')
('c', 'a', 'b')
('c', 'b', 'a')

길이가 2인 순열 :
('a', 'b')
('a', 'c')
('b', 'a')
('b', 'c')
('c', 'a')
('c', 'b')


In [45]:
from itertools import combinations
for c in combinations(items, 3):
    print(c)
    
for c in combinations(items, 2):
    print(c)
    
for c in combinations(items, 1):
    print(c)
    
#선택한 아이템은 가능한 후보의 컬렉션에서 제외됨

('a', 'b', 'c')
('a', 'b')
('a', 'c')
('b', 'c')
('a',)
('b',)
('c',)


In [51]:
#이를 보완해 같은 아이템을 두 번 이상 선택할 수 있게 하는 함수
from itertools import combinations_with_replacement
for c in combinations_with_replacement(items, 3):
    print(c)

('a', 'a', 'a')
('a', 'a', 'b')
('a', 'a', 'c')
('a', 'b', 'b')
('a', 'b', 'c')
('a', 'c', 'c')
('b', 'b', 'b')
('b', 'b', 'c')
('b', 'c', 'c')
('c', 'c', 'c')
